doc: Added Declarative pipeline syntax (to a few examples) to readme file
jenkinsci/lockable-resources-plugin pull request #412
Opened 2022-11-23 11:10 UTC by Jagrutiti

See [JENKINS-XXXXX](https://issues.jenkins.io/browse/JENKINS-XXXXX).

See #XXXXX

### Testing done

### Proposed changelog entries

- Entry 1: Issue, human-readable text
- […]

### Proposed upgrade guidelines

N/A

### Localizations

- [ ] English
- [ ] Franc
- [ ] Slovak
- [ ] Czech
- [ ] ...

### Submitter checklist

- [ ] The Jira / Github issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)).
  - Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during the upgrade.
- [ ] There is automated testing or an explanation that explains why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New public functions for internal use only are annotated with `@NoExternalUse`. In case it is used by non java code the `Used by {@code <panel>.jelly}` Javadocs are annotated.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease the future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
- [ ] Any localizations are transferred to *.properties files.

### Maintainer checklist

Before the changes are marked as `ready-for-merge`:

- [ ] There is at least one (1) approval for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] java code changes are tested by automated test.

2022-11-23 12:01 UTC, jimklimov commented
As noted on Gitter, I think it makes better sense to not convert but to clearly mark "Example for scripted pipeline" vs. "Example for declarative pipeline" since both are actively used, as different tools for different jobs.

Also, try to constrain the initial PR to focus on its feature changes. Seems it currently includes a version of commits already merged (or proposed elsewhere) to master and they show up in https://github.com/jenkinsci/lockable-resources-plugin/pull/412/files as changes for review: git-rebasing over current upstream/master can help.

2022-11-24 10:41 UTC, Jagrutiti commented
Hey @jimklimov 

I have added your suggestions and re-based the commit to master.

2022-11-24 14:58 UTC, jimklimov commented
Thanks for the rebase, still the "Changes" look odd. Was `[PULL_REQUEST_TEMPLATE.md](https://github.com/jenkinsci/lockable-resources-plugin/pull/412/files#diff-479755504b0aad0fed26047714591511b4d07c76bc8521171b87a5f16100f850)` and `[org/jenkins/plugins/lockableresources/actions/LockableResourcesRootAction/index.properties](https://github.com/jenkinsci/lockable-resources-plugin/pull/412/files#diff-812cc60f681b8439c0770757ab5795b69af89070a3c0a5c3e6cd95716821056f)` intentional? Or just grabbed by git from that other branch as a difference vs. master?

2022-11-24 15:01 UTC, mPokornyETM commented
When I am correct , this branch was created from `extend-documentation`
That explain the changes

2022-11-24 15:07 UTC, mPokornyETM commented
I propose to wait for this PR #403 and then re-merge master to this branch. After them you will see real changes.
@Jagrutiti thx for your time

2022-11-24 15:44 UTC, Jagrutiti commented
Hey @mPokornyETM , @jimklimov 

I had created my branch from `extend-documentation`. I am using this branch so that we do not face merging issues. [I had this discussion with @mPokornyETM.](https://github.com/jenkinsci/lockable-resources-plugin/issues/322#issuecomment-1321134534)

I wanted you guys to confirm:

1. Is my script example correct? 
2. Is it alright if I do that same for other examples in the `read.me` file?
3. Which branch shall I use as base branch to make my next PR?

2022-11-26 17:43 UTC, mPokornyETM commented
Thx I will wait until #403 is merged.  Then it will be easier to review the changes.  Pls wait next 1 or 2 days and I give you here a feedback.  Thx

2023-01-15 18:02 UTC, mPokornyETM requested changes

2023-01-17 15:28 UTC, mPokornyETM commented on README.md
> +Example for scripted pipeline:
```suggestion
```

2023-01-17 16:58 UTC, mPokornyETM approved these changes
LGTM

2023-01-17 17:17 UTC, merged